version: '3'
services:
  web:
    image: chatbot
    container_name: chatbot
    volumes:
      - ./:/app
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - COMPOSE_HTTP_TIMEOUT=200
      # - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: bash -c "make app"
